<a href="https://colab.research.google.com/github/Elmasri-Fathallah/Data-Analysis/blob/master/Agents_Performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

In [0]:
june_19 = pd.read_csv('june_19.csv', sep=',',header=0)
july_19 = pd.read_csv('july_19.csv', sep=',',header=0)
aug_19 = pd.read_csv('aug_19.csv', sep=',',header=0)
sept_19 = pd.read_csv('sept_19.csv', sep=',',header=0)
oct_19 = pd.read_csv('oct_19.csv', sep=',',header=0)
nov_19 = pd.read_csv('nov_19.csv', sep=',',header=0)

In [0]:
june_19 = june_19.drop(columns=['Column1','Unnamed: 0'])

# New Section

In [0]:
june_19

                                     Name   ACD Login  ...  Column3 Unnamed: 48
0                                 Overall  3867:49:34  ...      NaN         NaN
1                             Aoun, Kevin    70:50:12  ...  0:10:14         NaN
2            Yassen, Sameh Othman Mohamed    83:17:51  ...  0:06:13         NaN
3               Abuhamra, Abdelrahman A.A    84:09:44  ...  0:07:32         NaN
4   Sayed, Mohammad Moneer Mohammad Yehia    59:56:19  ...  0:07:27         NaN
5                 Mahareeq, Ahmed Mohamed    70:53:45  ...  0:08:27         NaN
6                               Adi, Iyas   135:36:55  ...  0:06:45         NaN
7                 Lail, Fouad Ahmed Fouad    44:38:57  ...  0:06:50         NaN
8                      Alshourbagi, Jalal   174:04:45  ...  0:06:24         NaN
9             Alhawali, Ahmad Abdulmannan   167:42:12  ...  0:06:26         NaN
10              Alsaeed Alhaj Ahmad, Majd   120:08:25  ...  0:07:46         NaN
11                       Alaaboud, Kanaan   126:33:36  ...  0:06:42         NaN
12                     Alkhaledova, Sarah   118:11:34  ...  0:06:22         NaN
13     Othman, Ibrahim Ahmed Ismail Ahmed    36:24:57  ...  0:08:01         NaN
14                        El Koft, Aladin   175:03:37  ...  0:06:46         NaN
15                    Ezzaldeen, Montaser   116:07:40  ...  0:06:15         NaN
16                        Zarour, Theodor   152:00:11  ...  0:06:13         NaN
17                      Elmeshaky, Nermin   162:28:53  ...      NaN         NaN
18    Elmasri, Fathallah Ismail Saleh Ali    92:07:09  ...      NaN         NaN
19                       Hussein, Mohamed     4:26:51  ...  0:07:25         NaN
20       Zayed, Ahmed Hassan Ahmed Hassan    59:01:20  ...  0:06:54         NaN
21            Elsayed, Ahmed Anwar Radwan    92:34:31  ...  0:06:50         NaN
22                         Nour, Mohammad    89:43:48  ...      NaN         NaN
23            Elbastawy, Inas Samir Sayed   126:27:52  ...      NaN         NaN
24                         Marcos, Bashar   159:28:52  ...      NaN         NaN
25                   El Halawani, Mohamed   100:13:44  ...      NaN         NaN
26             Osman, Tamer A-Ragab Osman   170:51:54  ...      NaN         NaN
27  Hassan, Mohamed Mohamed Ashraf Salama    86:42:23  ...      NaN         NaN
28                       Alagha, Abdullah    95:59:11  ...      NaN         NaN
29                       Mohamad, Alhasan   114:46:22  ...  0:08:56         NaN
30                 Almadhoun, Nehad M. M.    82:47:52  ...  0:08:09         NaN
31                         Alkotob, Ghada    18:47:49  ...  0:08:02         NaN
32                           Masoud, Anas    70:30:39  ...      NaN         NaN
33                      Hachachna, Mounir   130:50:09  ...      NaN         NaN
34                         Hamidi, Yasser   127:00:53  ...      NaN         NaN
35                      Al Haddad, Khaled   105:35:46  ...      NaN         NaN
36                       Abudayyeh, Qusai    49:22:23  ...      NaN         NaN
37            Sharaky, Samar Ahmed Hassan    48:45:41  ...      NaN         NaN
38      Ibrahim, Heba Abdelalem Abdelnabi    58:33:10  ...      NaN         NaN
39                          Kenzi, Techfa    85:01:42  ...      NaN         NaN

[40 rows x 47 columns]

In [0]:
july_19

                                     Name   ACD Login  ...          Team     Site
0                                 Overall  5555:16:45  ...           NaN      NaN
1                            Masoud, Anas    98:17:26  ...        Mshwah   Berlin
2                 Mahareeq, Ahmed Mohamed    91:30:08  ...        Mshwah   Berlin
3                          Nour, Mohammad    57:40:44  ...       Elmasri   Berlin
4                       Al Haddad, Khaled   174:57:11  ...        Mshwah   Berlin
5                          Marcos, Bashar   151:29:24  ...        Mshwah   Berlin
6                        Abudayyeh, Qusai   103:58:58  ...       Elmasri   Berlin
7                       Elmeshaky, Nermin   171:41:12  ...       Elmasri   Berlin
8     Elmasri, Fathallah Ismail Saleh Ali    21:50:25  ...  Team Manager   Berlin
9             Elbastawy, Inas Samir Sayed   192:46:17  ...       Elmasri   Berlin
10            Sharaky, Samar Ahmed Hassan    84:09:41  ...       Elmasri   Berlin
11                       Alaaboud, Kanaan   130:10:28  ...        Mshwah   Berlin
12                       Alagha, Abdullah   149:15:28  ...        Mshwah   Berlin
13                   El Halawani, Mohamed    30:04:29  ...       Elmasri   Berlin
14  Sayed, Mohammad Moneer Mohammad Yehia   105:47:42  ...        Mshwah   Berlin
15                     Alkhaledova, Sarah   167:49:45  ...        Mshwah   Berlin
16      Ibrahim, Heba Abdelalem Abdelnabi   177:13:50  ...        Mshwah   Berlin
17                         Hamidi, Yasser   181:19:07  ...       Elmasri   Berlin
18            Alhawali, Ahmad Abdulmannan   155:41:54  ...        Mshwah   Berlin
19  Hassan, Mohamed Mohamed Ashraf Salama    77:16:42  ...       Elmasri   Berlin
20             Osman, Tamer A-Ragab Osman    81:05:34  ...       Mentors   Berlin
21                          Kenzi, Techfa   193:42:10  ...        Mshwah   Berlin
22              Abuhamra, Abdelrahman A.A    93:30:50  ...       Elmasri   Berlin
23                      Hachachna, Mounir   201:08:12  ...       Elmasri  BERHome
24                     Alshourbagi, Jalal   179:20:04  ...        Mshwah   Berlin
25           Yassen, Sameh Othman Mohamed   108:04:05  ...        Mshwah   Berlin
26                       Hussein, Mohamed   100:38:12  ...       Elmasri   Berlin
27                Lail, Fouad Ahmed Fouad   119:29:46  ...       Elmasri   Berlin
28                        El Koft, Aladin   205:18:20  ...        Mshwah   Berlin
29                              Adi, Iyas   153:53:06  ...        Mshwah   Berlin
30                         Alkotob, Ghada   206:40:21  ...        Mshwah   Berlin
31                        Zarour, Theodor   139:01:28  ...        Mshwah   Berlin
32                            Aoun, Kevin    34:57:57  ...        Mshwah   Berlin
33       Zayed, Ahmed Hassan Ahmed Hassan    13:03:26  ...        Mshwah   Berlin
34                    Ezzaldeen, Montaser   136:22:13  ...        Mshwah   Berlin
35                 Almadhoun, Nehad M. M.     9:00:33  ...        Mshwah   Berlin
36     Othman, Ibrahim Ahmed Ismail Ahmed    36:13:50  ...       Elmasri   Berlin
37                        Alkurdi, Mayiar   145:08:16  ...       Elmasri   Berlin
38                          Hafez, Bisher   163:55:03  ...        Mshwah   Berlin
39                       Mohamad, Alhasan    79:26:13  ...        Mshwah   Berlin
40                          Irsheid, Eyas    80:39:29  ...        Mshwah   Berlin
41    Ashour, Mohamed Eslam Mahmoud Ahmed   167:29:41  ...        Mshwah   Berlin
42                            Tooma, Ward   114:51:25  ...        Mshwah   Berlin
43                            Mahdi, Dana    67:14:18  ...       Elmasri   Berlin
44                         Al Haj, Mamoun   149:43:56  ...        Mshwah   Berlin
45             Hallaq, Saif Omar Mohammad    69:28:44  ...       Elmasri   Berlin
46   Ragab, Ahmed Ayman Ahmed Abdelmaguid    72:27:47  ...       Elmasri   Berlin
47              Alsaeed Alhaj Ahmad, Majd    63:16:18  ...        Mshwah   Berlin
48            Elsayed, Ahmed Anwar Radwan    47:04:37  ...       Elmasri   Berlin

[49 rows x 44 columns]

In [0]:
aug_19

                                     Name   ACD Login  ...          Team     Site
0                                 Overall  5555:16:45  ...           NaN      NaN
1                            Masoud, Anas    98:17:26  ...        Mshwah   Berlin
2                 Mahareeq, Ahmed Mohamed    91:30:08  ...        Mshwah   Berlin
3                          Nour, Mohammad    57:40:44  ...       Elmasri   Berlin
4                       Al Haddad, Khaled   174:57:11  ...        Mshwah   Berlin
5                          Marcos, Bashar   151:29:24  ...        Mshwah   Berlin
6                        Abudayyeh, Qusai   103:58:58  ...       Elmasri   Berlin
7                       Elmeshaky, Nermin   171:41:12  ...       Elmasri   Berlin
8     Elmasri, Fathallah Ismail Saleh Ali    21:50:25  ...  Team Manager   Berlin
9             Elbastawy, Inas Samir Sayed   192:46:17  ...       Elmasri   Berlin
10            Sharaky, Samar Ahmed Hassan    84:09:41  ...       Elmasri   Berlin
11                       Alaaboud, Kanaan   130:10:28  ...        Mshwah   Berlin
12                       Alagha, Abdullah   149:15:28  ...        Mshwah   Berlin
13                   El Halawani, Mohamed    30:04:29  ...       Elmasri   Berlin
14  Sayed, Mohammad Moneer Mohammad Yehia   105:47:42  ...        Mshwah   Berlin
15                     Alkhaledova, Sarah   167:49:45  ...        Mshwah   Berlin
16      Ibrahim, Heba Abdelalem Abdelnabi   177:13:50  ...        Mshwah   Berlin
17                         Hamidi, Yasser   181:19:07  ...       Elmasri   Berlin
18            Alhawali, Ahmad Abdulmannan   155:41:54  ...        Mshwah   Berlin
19  Hassan, Mohamed Mohamed Ashraf Salama    77:16:42  ...       Elmasri   Berlin
20             Osman, Tamer A-Ragab Osman    81:05:34  ...       Mentors   Berlin
21                          Kenzi, Techfa   193:42:10  ...        Mshwah   Berlin
22              Abuhamra, Abdelrahman A.A    93:30:50  ...       Elmasri   Berlin
23                      Hachachna, Mounir   201:08:12  ...       Elmasri  BERHome
24                     Alshourbagi, Jalal   179:20:04  ...        Mshwah   Berlin
25           Yassen, Sameh Othman Mohamed   108:04:05  ...        Mshwah   Berlin
26                       Hussein, Mohamed   100:38:12  ...       Elmasri   Berlin
27                Lail, Fouad Ahmed Fouad   119:29:46  ...       Elmasri   Berlin
28                        El Koft, Aladin   205:18:20  ...        Mshwah   Berlin
29                              Adi, Iyas   153:53:06  ...        Mshwah   Berlin
30                         Alkotob, Ghada   206:40:21  ...        Mshwah   Berlin
31                        Zarour, Theodor   139:01:28  ...        Mshwah   Berlin
32                            Aoun, Kevin    34:57:57  ...        Mshwah   Berlin
33       Zayed, Ahmed Hassan Ahmed Hassan    13:03:26  ...        Mshwah   Berlin
34                    Ezzaldeen, Montaser   136:22:13  ...        Mshwah   Berlin
35                 Almadhoun, Nehad M. M.     9:00:33  ...        Mshwah   Berlin
36     Othman, Ibrahim Ahmed Ismail Ahmed    36:13:50  ...       Elmasri   Berlin
37                        Alkurdi, Mayiar   145:08:16  ...       Elmasri   Berlin
38                          Hafez, Bisher   163:55:03  ...        Mshwah   Berlin
39                       Mohamad, Alhasan    79:26:13  ...        Mshwah   Berlin
40                          Irsheid, Eyas    80:39:29  ...        Mshwah   Berlin
41    Ashour, Mohamed Eslam Mahmoud Ahmed   167:29:41  ...        Mshwah   Berlin
42                            Tooma, Ward   114:51:25  ...        Mshwah   Berlin
43                            Mahdi, Dana    67:14:18  ...       Elmasri   Berlin
44                         Al Haj, Mamoun   149:43:56  ...        Mshwah   Berlin
45             Hallaq, Saif Omar Mohammad    69:28:44  ...       Elmasri   Berlin
46   Ragab, Ahmed Ayman Ahmed Abdelmaguid    72:27:47  ...       Elmasri   Berlin
47              Alsaeed Alhaj Ahmad, Majd    63:16:18  ...        Mshwah   Berlin
48            Elsayed, Ahmed Anwar Radwan    47:04:37  ...       Elmasri   Berlin

[49 rows x 44 columns]

In [0]:
sept_19

                                        Name   ACD Login  ...     Team     Site
0                                    Overall  3678:42:28  ...      NaN      NaN
1                           Hussein, Mohamed    77:21:01  ...  Elmasri   Berlin
2                Elbastawy, Inas Samir Sayed    89:12:27  ...  Elmasri   Berlin
3                            Alkurdi, Mayiar   167:29:05  ...  Elmasri   Berlin
4                             Alkotob, Ghada   159:39:25  ...   Mshwah   Berlin
5                              Hafez, Bisher   154:55:11  ...   Mshwah   Berlin
6                             Nour, Mohammad    34:19:20  ...  Elmasri   Berlin
7                          Elmeshaky, Nermin   133:25:40  ...  Elmasri   Berlin
8                                Mahdi, Dana    38:18:11  ...  Elmasri   Berlin
9                 Osman, Tamer A-Ragab Osman   173:07:49  ...  Mentors   Berlin
10                 Alsaeed Alhaj Ahmad, Majd    62:03:27  ...   Mshwah   Berlin
11                   Mahareeq, Ahmed Mohamed    64:39:58  ...   Mshwah   Berlin
12       Ashour, Mohamed Eslam Mahmoud Ahmed   176:07:56  ...   Mshwah   Berlin
13               Elsayed, Ahmed Anwar Radwan    34:41:18  ...  Elmasri   Berlin
14                         Al Haddad, Khaled   202:31:03  ...   Mshwah   Berlin
15                      El Halawani, Mohamed    96:08:52  ...  Elmasri   Berlin
16               Alhawali, Ahmad Abdulmannan   151:28:11  ...   Mshwah   Berlin
17                         Hachachna, Mounir   109:41:51  ...  Elmasri  BERHome
18                 Abuhamra, Abdelrahman A.A    65:32:08  ...  Elmasri   Berlin
19      Ragab, Ahmed Ayman Ahmed Abdelmaguid    46:20:14  ...  Elmasri   Berlin
20                        Alshourbagi, Jalal   185:57:25  ...   Mshwah   Berlin
21                             Kenzi, Techfa   192:54:51  ...   Mshwah   Berlin
22                   Lail, Fouad Ahmed Fouad    82:52:21  ...  Elmasri   Berlin
23               Sharaky, Samar Ahmed Hassan    48:01:31  ...  Elmasri   Berlin
24     Hassan, Mohamed Mohamed Ashraf Salama    21:16:26  ...  Elmasri   Berlin
25                           Zarour, Theodor   165:29:51  ...   Mshwah   Berlin
26                Hallaq, Saif Omar Mohammad    86:09:47  ...  Elmasri   Berlin
27                            Al Haj, Mamoun   129:45:57  ...   Mshwah   Berlin
28                          Mohamad, Alhasan    26:23:25  ...   Mshwah   Berlin
29                        Alkhaledova, Sarah    82:39:20  ...   Mshwah   Berlin
30         Ibrahim, Heba Abdelalem Abdelnabi   141:17:23  ...   Mshwah   Berlin
31                          Abudayyeh, Qusai    71:33:13  ...  Elmasri   Berlin
32                            Hamidi, Yasser   148:08:12  ...  Elmasri   Berlin
33        Othman, Ibrahim Ahmed Ismail Ahmed     5:25:32  ...  Elmasri   Berlin
34              Yassen, Sameh Othman Mohamed    67:17:43  ...   Mshwah   Berlin
35                       Ezzaldeen, Montaser    58:59:27  ...   Mshwah   Berlin
36                           El Koft, Aladin   103:59:18  ...   Mshwah   Berlin
37          Elsharabassi, Ahmed Atef Ibrahim     6:36:26  ...   Mshwah   Berlin
38                              Kreker, Nour     6:01:41  ...   Mshwah   Berlin
39                           Alhaddad, Feras     5:57:51  ...   Mshwah   Berlin
40  Elhakim, Heidi Hany Zaki Suliman Mohamed     4:51:41  ...   Mshwah   Berlin

[41 rows x 44 columns]

In [0]:
oct_19

                                        Name   ACD Login  ...     Team     Site
0                                    Overall  4229:25:48  ...      NaN      NaN
1                        Ezzaldeen, Montaser     8:46:10  ...   Mshwah   Berlin
2                          Hachachna, Mounir    89:16:04  ...  Elmasri  BERHome
3               Yassen, Sameh Othman Mohamed    31:39:04  ...   Mshwah   Berlin
4                          Al Haddad, Khaled    26:11:28  ...   Mshwah   Berlin
5                    Mahareeq, Ahmed Mohamed    94:20:29  ...   Mshwah   Berlin
6                Alhawali, Ahmad Abdulmannan    16:17:08  ...   Mshwah   Berlin
7                           Hussein, Mohamed    51:01:54  ...  Elmasri   Berlin
8   Elhakim, Heidi Hany Zaki Suliman Mohamed    98:54:07  ...   Mshwah   Berlin
9                                Mahdi, Dana   100:52:11  ...  Elmasri   Berlin
10     Hassan, Mohamed Mohamed Ashraf Salama    85:22:55  ...  Elmasri   Berlin
11                           Alkurdi, Mayiar   152:44:24  ...  Elmasri   Berlin
12          Elsharabassi, Ahmed Atef Ibrahim   168:02:01  ...   Mshwah   Berlin
13                        Alshourbagi, Jalal   143:20:30  ...   Mshwah   Berlin
14       Ashour, Mohamed Eslam Mahmoud Ahmed   104:51:35  ...   Mshwah   Berlin
15                 Alsaeed Alhaj Ahmad, Majd   101:30:18  ...   Mshwah   Berlin
16                          Abudayyeh, Qusai    83:26:06  ...  Elmasri   Berlin
17                 Abuhamra, Abdelrahman A.A    82:17:26  ...  Elmasri   Berlin
18                            Ghanoum, Usama   172:29:16  ...   Mshwah   Berlin
19               Sharaky, Samar Ahmed Hassan    73:00:59  ...  Elmasri   Berlin
20                Hallaq, Saif Omar Mohammad    82:35:54  ...  Elmasri   Berlin
21                           Alhaddad, Feras   157:02:45  ...   Mshwah   Berlin
22                Osman, Tamer A-Ragab Osman   171:52:59  ...  Mentors   Berlin
23                            Alkotob, Ghada   122:34:39  ...   Mshwah   Berlin
24                            Kabbani, Karam   134:16:38  ...   Mshwah   Berlin
25                            Hamidi, Yasser   174:25:01  ...  Elmasri   Berlin
26                            Al Haj, Mamoun   151:46:11  ...   Mshwah   Berlin
27         Ibrahim, Heba Abdelalem Abdelnabi   162:33:50  ...   Mshwah   Berlin
28                      El Halawani, Mohamed    63:33:11  ...  Elmasri   Berlin
29                             Kenzi, Techfa   201:30:29  ...   Mshwah   Berlin
30                           El Koft, Aladin   172:57:47  ...   Mshwah   Berlin
31                             Hafez, Bisher   171:49:10  ...   Mshwah   Berlin
32                              Kreker, Nour   175:21:35  ...   Mshwah   Berlin
33                   Lail, Fouad Ahmed Fouad    90:49:27  ...  Elmasri   Berlin
34                         Elmeshaky, Nermin   181:26:22  ...  Elmasri   Berlin
35                        Alkhaledova, Sarah   156:29:07  ...   Mshwah   Berlin
36                           Zarour, Theodor   173:56:38  ...   Mshwah   Berlin

[37 rows x 44 columns]

In [0]:
nov_19

                                        Name   ACD Login  ...     Team     Site
0                                    Overall  3542:54:53  ...      NaN      NaN
1           Elsharabassi, Ahmed Atef Ibrahim    56:35:42  ...   Mshwah   Berlin
2                 Alagrab, Ahmed Abdelfattah    64:06:55  ...   Mshwah   Berlin
3                              Moualla, Yara    60:01:00  ...   Mshwah   Berlin
4                    Mahareeq, Ahmed Mohamed    14:04:01  ...   Mshwah   Berlin
5                          Hachachna, Mounir   107:41:08  ...  Elmasri  BERHome
6                          Aldarwish, Bashar    93:45:05  ...   Mshwah   Berlin
7   Elhakim, Heidi Hany Zaki Suliman Mohamed    75:40:16  ...   Mshwah   Berlin
8                           Abudayyeh, Qusai    25:57:46  ...  Elmasri   Berlin
9                Sharaky, Samar Ahmed Hassan    29:21:28  ...  Elmasri   Berlin
10                          Hussein, Mohamed    49:27:46  ...  Elmasri   Berlin
11                           Alkurdi, Mayiar   114:24:43  ...  Elmasri   Berlin
12                 Alsaeed Alhaj Ahmad, Majd    52:51:01  ...   Mshwah   Berlin
13                               Mahdi, Dana    65:13:09  ...  Elmasri   Berlin
14                            Hamidi, Yasser    93:37:02  ...  Elmasri   Berlin
15       Ashour, Mohamed Eslam Mahmoud Ahmed   117:08:02  ...   Mshwah   Berlin
16                Hallaq, Saif Omar Mohammad    80:37:30  ...  Elmasri   Berlin
17              Yassen, Sameh Othman Mohamed    72:52:25  ...   Mshwah   Berlin
18                            Alkotob, Ghada   113:22:05  ...   Mshwah   Berlin
19                         Al Haddad, Khaled   111:05:09  ...   Mshwah   Berlin
20                        Alshourbagi, Jalal   170:49:00  ...   Mshwah   Berlin
21         Ibrahim, Heba Abdelalem Abdelnabi   114:11:34  ...   Mshwah   Berlin
22                      El Halawani, Mohamed    34:08:49  ...  Elmasri   Berlin
23                         Elmeshaky, Nermin   138:41:12  ...  Elmasri   Berlin
24               Alhawali, Ahmad Abdulmannan   163:24:40  ...   Mshwah   Berlin
25                             Kenzi, Techfa   124:19:43  ...   Mshwah   Berlin
26                            Al Haj, Mamoun   120:03:39  ...   Mshwah   Berlin
27                   Lail, Fouad Ahmed Fouad    30:14:17  ...  Elmasri   Berlin
28                 Abuhamra, Abdelrahman A.A    76:49:23  ...  Elmasri   Berlin
29                             Hafez, Bisher   120:25:02  ...   Mshwah   Berlin
30                           Alhaddad, Feras   166:04:12  ...   Mshwah   Berlin
31                            Kabbani, Karam   101:49:36  ...   Mshwah   Berlin
32                           El Koft, Aladin   115:11:39  ...   Mshwah   Berlin
33                            Ghanoum, Usama   181:27:19  ...   Mshwah   Berlin
34                        Alkhaledova, Sarah   143:31:42  ...   Mshwah   Berlin
35                              Kreker, Nour   161:06:45  ...   Mshwah   Berlin
36                           Zarour, Theodor   182:44:08  ...   Mshwah   Berlin

[37 rows x 44 columns]

In [0]:
year_19 = pd.concat(['jun_19','july_19','aug_19','sept_19','oct_19','nov_19'])

TypeError: ignored

In [0]:
print(nov_19.dtypes)

Name                   object
ACD Login              object
Hand                    int64
AHT                    object
ATT                    object
ACW                    object
HLD                    object
Ring                   object
Avail                  object
E-Mail Hand             int64
Avail + AUX8           object
Break AUX1+AUX2        object
Lunch AUX1             object
Short AUX2             object
Social AUX21           object
Research AUX3          object
L2/L3/PSN AUX31        object
Training AUX4         float64
Training AUX5          object
Nesting AUX51          object
PEP/QM AUX52           object
Callback AUX6         float64
Mentoring AUX7         object
E-Mail AUX8            object
Meeting AUX9           object
System Issue AUX91     object
Login AUX0             object
Case Logs               int64
Log.%                  object
Short.%                object
NPS                    object
Transfer Attempts     float64
Transfer Rate          object
CSAT Answers          float64
Answer Rate            object
AM Transfers          float64
Tenure                  int64
E-Mail NPS             object
E-Mail CES             object
E-Mail FTR             object
Country                object
Avaya Id              float64
Team                   object
Site                   object
dtype: object